# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(910, 669)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        window.setFont(font)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.view = QtWidgets.QGraphicsView(self.centralwidget)
        self.view.setObjectName("view")
        self.verticalLayout.addWidget(self.view)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 0, 10, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.opt_hex = QtWidgets.QRadioButton(self.centralwidget)
        self.opt_hex.setMinimumSize(QtCore.QSize(0, 28))
        self.opt_hex.setMaximumSize(QtCore.QSize(140, 28))
        self.opt_hex.setChecked(True)
        self.opt_hex.setObjectName("opt_hex")
        self.horizontalLayout_2.addWidget(self.opt_hex)
        self.opt_square = QtWidgets.QRadioButton(self.centralwidget)
        self.opt_square.setMinimumSize(QtCore.QSize(0, 28))
        self.opt_square.setMaximumSize(QtCore.QSize(140, 28))
        self.opt_square.setObjectName("opt_square")
        self.horizontalLayout_2.addWidget(self.opt_square)
        self.spb_width = QtWidgets.QSpinBox(self.centralwidget)
        self.spb_width.setMinimumSize(QtCore.QSize(38, 28))
        self.spb_width.setMaximumSize(QtCore.QSize(80, 28))
        self.spb_width.setMinimum(1)
        self.spb_width.setMaximum(999)
        self.spb_width.setProperty("value", 30)
        self.spb_width.setObjectName("spb_width")
        self.horizontalLayout_2.addWidget(self.spb_width)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(10, 0))
        self.label_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spb_height = QtWidgets.QSpinBox(self.centralwidget)
        self.spb_height.setMinimumSize(QtCore.QSize(38, 28))
        self.spb_height.setMaximumSize(QtCore.QSize(80, 28))
        self.spb_height.setMinimum(1)
        self.spb_height.setMaximum(999)
        self.spb_height.setProperty("value", 30)
        self.spb_height.setObjectName("spb_height")
        self.horizontalLayout_2.addWidget(self.spb_height)
        self.btn_make = QtWidgets.QToolButton(self.centralwidget)
        self.btn_make.setMinimumSize(QtCore.QSize(35, 35))
        self.btn_make.setObjectName("btn_make")
        self.horizontalLayout_2.addWidget(self.btn_make)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.btn_zoom_plus = QtWidgets.QToolButton(self.centralwidget)
        self.btn_zoom_plus.setObjectName("btn_zoom_plus")
        self.horizontalLayout_4.addWidget(self.btn_zoom_plus)
        self.btn_zoom_minus = QtWidgets.QToolButton(self.centralwidget)
        self.btn_zoom_minus.setObjectName("btn_zoom_minus")
        self.horizontalLayout_4.addWidget(self.btn_zoom_minus)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.chk_displayCoords = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_displayCoords.setChecked(True)
        self.chk_displayCoords.setObjectName("chk_displayCoords")
        self.horizontalLayout_4.addWidget(self.chk_displayCoords)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txt_coords = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_coords.setMinimumSize(QtCore.QSize(183, 0))
        self.txt_coords.setObjectName("txt_coords")
        self.verticalLayout_2.addWidget(self.txt_coords)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btn_updateSelection = QtWidgets.QToolButton(self.centralwidget)
        self.btn_updateSelection.setMinimumSize(QtCore.QSize(132, 35))
        self.btn_updateSelection.setMaximumSize(QtCore.QSize(132, 1000))
        self.btn_updateSelection.setObjectName("btn_updateSelection")
        self.horizontalLayout_3.addWidget(self.btn_updateSelection)
        self.btn_toClipboard = QtWidgets.QToolButton(self.centralwidget)
        self.btn_toClipboard.setMinimumSize(QtCore.QSize(84, 35))
        self.btn_toClipboard.setMaximumSize(QtCore.QSize(84, 1000))
        self.btn_toClipboard.setObjectName("btn_toClipboard")
        self.horizontalLayout_3.addWidget(self.btn_toClipboard)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 2)
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 21))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(window)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuFichier.addAction(self.actionQuitter)
        self.menubar.addAction(self.menuFichier.menuAction())

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "MainWindow"))
        self.lbl_title.setText(_translate("window", "Grid Viewer"))
        self.label.setText(_translate("window", "Update Grid"))
        self.opt_hex.setText(_translate("window", "Hexagonal grid"))
        self.opt_square.setText(_translate("window", "Square grid"))
        self.label_2.setText(_translate("window", "X"))
        self.btn_make.setText(_translate("window", ">>"))
        self.label_3.setText(_translate("window", "Zoom"))
        self.btn_zoom_plus.setText(_translate("window", "+"))
        self.btn_zoom_minus.setText(_translate("window", "-"))
        self.chk_displayCoords.setText(_translate("window", "Display coordinates"))
        self.btn_updateSelection.setText(_translate("window", "Update selection"))
        self.btn_toClipboard.setText(_translate("window", "To clipboard"))
        self.menuFichier.setTitle(_translate("window", "Fichier"))
        self.actionQuitter.setText(_translate("window", "Quitter"))

