# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(910, 658)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        window.setFont(font)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.frame_tools = QtWidgets.QFrame(self.centralwidget)
        self.frame_tools.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_tools.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tools.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tools.setObjectName("frame_tools")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_tools)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_new_grid = QtWidgets.QPushButton(self.frame_tools)
        self.btn_new_grid.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_new_grid.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btn_new_grid.setObjectName("btn_new_grid")
        self.horizontalLayout_2.addWidget(self.btn_new_grid)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cb_functions = QtWidgets.QComboBox(self.frame_tools)
        self.cb_functions.setObjectName("cb_functions")
        self.horizontalLayout_2.addWidget(self.cb_functions)
        self.txt_args = QtWidgets.QLineEdit(self.frame_tools)
        self.txt_args.setMinimumSize(QtCore.QSize(200, 0))
        self.txt_args.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txt_args.setObjectName("txt_args")
        self.horizontalLayout_2.addWidget(self.txt_args)
        self.chk_expand = QtWidgets.QCheckBox(self.frame_tools)
        self.chk_expand.setMinimumSize(QtCore.QSize(100, 0))
        self.chk_expand.setMaximumSize(QtCore.QSize(100, 16777215))
        self.chk_expand.setObjectName("chk_expand")
        self.horizontalLayout_2.addWidget(self.chk_expand)
        self.btn_run = QtWidgets.QToolButton(self.frame_tools)
        self.btn_run.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_run.setMaximumSize(QtCore.QSize(16777215, 20))
        self.btn_run.setObjectName("btn_run")
        self.horizontalLayout_2.addWidget(self.btn_run)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_list_view = QtWidgets.QPushButton(self.frame_tools)
        self.btn_list_view.setObjectName("btn_list_view")
        self.horizontalLayout_2.addWidget(self.btn_list_view)
        self.verticalLayout.addWidget(self.frame_tools)
        self.view = QtWidgets.QGraphicsView(self.centralwidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.view.setFont(font)
        self.view.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.view.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.view.setViewportUpdateMode(QtWidgets.QGraphicsView.BoundingRectViewportUpdate)
        self.view.setObjectName("view")
        self.verticalLayout.addWidget(self.view)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.btn_zoom_plus = QtWidgets.QToolButton(self.centralwidget)
        self.btn_zoom_plus.setObjectName("btn_zoom_plus")
        self.horizontalLayout_4.addWidget(self.btn_zoom_plus)
        self.btn_zoom_minus = QtWidgets.QToolButton(self.centralwidget)
        self.btn_zoom_minus.setObjectName("btn_zoom_minus")
        self.horizontalLayout_4.addWidget(self.btn_zoom_minus)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.chk_displayCoords = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_displayCoords.setChecked(True)
        self.chk_displayCoords.setObjectName("chk_displayCoords")
        self.horizontalLayout_4.addWidget(self.chk_displayCoords)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 2)
        window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(window)
        self.actionQuitter.setObjectName("actionQuitter")

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)
        window.setTabOrder(self.view, self.btn_new_grid)
        window.setTabOrder(self.btn_new_grid, self.cb_functions)
        window.setTabOrder(self.cb_functions, self.txt_args)
        window.setTabOrder(self.txt_args, self.chk_expand)
        window.setTabOrder(self.chk_expand, self.btn_list_view)
        window.setTabOrder(self.btn_list_view, self.btn_zoom_plus)
        window.setTabOrder(self.btn_zoom_plus, self.btn_zoom_minus)
        window.setTabOrder(self.btn_zoom_minus, self.chk_displayCoords)
        window.setTabOrder(self.chk_displayCoords, self.lbl_title)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "GridViewer"))
        self.lbl_title.setText(_translate("window", "Grid Viewer"))
        self.btn_new_grid.setText(_translate("window", "New Grid"))
        self.chk_expand.setText(_translate("window", "Auto-expand"))
        self.btn_run.setText(_translate("window", ">"))
        self.btn_list_view.setText(_translate("window", "List View"))
        self.label_3.setText(_translate("window", "Zoom"))
        self.btn_zoom_plus.setText(_translate("window", "+"))
        self.btn_zoom_minus.setText(_translate("window", "-"))
        self.chk_displayCoords.setText(_translate("window", "Display coordinates"))
        self.actionQuitter.setText(_translate("window", "Quitter"))

